/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'audiomark_app.Release+Ethos-MPS3-Corstone-310' 
 * Target:  'Release+Ethos-MPS3-Corstone-310' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Arm::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.22.8 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55
/* GorgonMeducer::Utilities&Performance Counter:perf_counter:Core&Library@1.9.11 */
#define __PERF_COUNTER_CFG_USE_SYSTICK_WRAPPER__
/* tensorflow::Machine Learning:TensorFlow:Kernel&Ethos-U@1.22.8 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define TF_LITE_DISABLE_X86_NEON 1
        //#define TF_LITE_STRIP_ERROR_STRINGS 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
