/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'audiomark_app.Release+VHT_M85' 
 * Target:  'Release+VHT_M85' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM85.h"

/* GorgonMeducer::Utilities&Performance Counter:perf_counter:Core&Library@1.9.11 */
#define __PERF_COUNTER__


#endif /* RTE_COMPONENTS_H */
