/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'testanr.Release+MPS3-Corstone-310' 
 * Target:  'Release+MPS3-Corstone-310' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* GorgonMeducer::Utilities&Performance Counter:perf_counter:Core&Library@1.9.11 */
#define __PERF_COUNTER_CFG_USE_SYSTICK_WRAPPER__


#endif /* PRE_INCLUDE_GLOBAL_H */
